name: Dependency Review

on:
  pull_request:
    branches: [main, master, develop]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          # Allow known safe ecosystems; defaults are fine for npm
